name: flutter_bluetooth_serial_example
version: 0.4.0
description: Demonstrates how to use the `flutter_bluetooth_serial` plugin.
authors:
  - Patryk Ludwikowski <patryk.ludwikowski.7@gmail.com>
homepage: https://github.com/edufolly/flutter_bluetooth_serial/tree/master/example/

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  scoped_model: ^2.0.0-nullsafety.0
  cupertino_icons: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_bluetooth_serial:
    path: ../
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
