name: flutter_bluetooth_serial
version: 0.2.2
description: A basic Flutter Bluetooth Serial library
authors: 
- Eduardo Folly <edufolly@gmail.com>
- Patryk Ludwikowski <patryk.ludwikowski.7@gmail.com>
homepage: https://github.com/edufolly/flutter_bluetooth_serial
repository: https://github.com/edufolly/flutter_bluetooth_serial
issue_tracker: https://github.com/edufolly/flutter_bluetooth_serial/issues

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: io.github.edufolly.flutterbluetoothserial
    pluginClass: FlutterBluetoothSerialPlugin

environment:
  sdk: ">=2.0.0-a <3.0.0"
